inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'bin/**/*'
    - 'vendor/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 7

RSpec/NestedGroups:
  Max: 4

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Whitelist:
    - 'touch'
    - 'update_attribute'

Style/Documentation:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
